// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-D1AiAa5s7p0_owFYU6BT0xclQCSMIc',
    appId: '1:367197570146:web:949de653bda2abb4587d3b',
    messagingSenderId: '367197570146',
    projectId: 'doorcareuser-8283c',
    authDomain: 'doorcareuser-8283c.firebaseapp.com',
    storageBucket: 'doorcareuser-8283c.appspot.com',
    measurementId: 'G-K0SSKS4697',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7kEUiPFblJYeYpX6VUpW0lHDC-LOI4yI',
    appId: '1:367197570146:android:aadebc508931aa65587d3b',
    messagingSenderId: '367197570146',
    projectId: 'doorcareuser-8283c',
    storageBucket: 'doorcareuser-8283c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4K2K3iQY4XT-fvLp5wFCQ-atg5-6lAGk',
    appId: '1:367197570146:ios:4a43432e75efd672587d3b',
    messagingSenderId: '367197570146',
    projectId: 'doorcareuser-8283c',
    storageBucket: 'doorcareuser-8283c.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4K2K3iQY4XT-fvLp5wFCQ-atg5-6lAGk',
    appId: '1:367197570146:ios:4a43432e75efd672587d3b',
    messagingSenderId: '367197570146',
    projectId: 'doorcareuser-8283c',
    storageBucket: 'doorcareuser-8283c.appspot.com',
    iosBundleId: 'com.example.doorCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo-D1AiAa5s7p0_owFYU6BT0xclQCSMIc',
    appId: '1:367197570146:web:9ed213aade558101587d3b',
    messagingSenderId: '367197570146',
    projectId: 'doorcareuser-8283c',
    authDomain: 'doorcareuser-8283c.firebaseapp.com',
    storageBucket: 'doorcareuser-8283c.appspot.com',
    measurementId: 'G-MK5QHRDPY6',
  );
}
